[project]
name = "hello-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ag2>=0.7.2",
]

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
]
